runtime: custom
env: flex
entrypoint: gunicorn --bind :$PORT --workers 1 --threads 2 --chdir app/ app.wsgi:application --timeout 6000 --preload

runtime_config:
  python_version: 3.8.5

manual_scaling:
  instances: 2
resources:
  cpu: 2
  memory_gb: 10
  disk_size_gb: 20


handlers:
  - url: /static 
    static_dir: static/
  - url: /.*
    script: auto